### PR TITLE
Pull request for issues #7 and #9

### PR DESCRIPTION
**Pull request by GarrySan**
Fires loadObs() function every 5 minutes inorder to update the map with new locations from the Google sheets

### CODE REVIEW

**Comment by GarrySan** [comment]
@ivanoats

**Comment by GarrySan** [comment]
@ivanoats can this be merged?

**Comment by ivanoats** [comment]
Yes, Looks Good To Me (LGTM)

**Comment by GarrySan** [comment]
Can you merge it?

**Pull request merged**
